import esbuild from "esbuild";
import process from "process";
import path from "path";
import builtins from "builtin-modules";
import { sassPlugin } from "esbuild-sass-plugin";

/**
 * zod's `locales/index.js` barrel re-exports error messages for ~20 languages
 * and is consumed as a namespace object (`z.locales`), so esbuild cannot
 * tree-shake it — it accounted for ~197 KB, over a quarter of the whole plugin.
 *
 * We only ever use zod's default (English) errors: nothing in `src` touches
 * `z.locales`, `errorMap`, `setErrorMap` or `z.config`. Swapping the barrel for
 * an `en`-only stub keeps validation messages identical.
 *
 * If a future change needs another zod locale, delete this plugin — the bundle
 * grows back, but nothing silently misbehaves.
 */
const stripUnusedZodLocales = {
  name: "strip-unused-zod-locales",
  setup(build) {
    build.onResolve({ filter: /locales[\\/]index\.js$/ }, (args) => {
      if (!args.importer.includes(`${path.sep}zod${path.sep}`)) {
        return null;
      }
      return { path: args.path, namespace: "zod-locales-stub" };
    });

    build.onLoad({ filter: /.*/, namespace: "zod-locales-stub" }, () => ({
      contents: `export { default as en } from ${JSON.stringify(
        path.resolve("node_modules/zod/v4/locales/en.js"),
      )};`,
      loader: "js",
      resolveDir: process.cwd(),
    }));
  },
};

// Determine if we're in production mode
const isProd = process.argv.includes("--production");
const isDebug = process.argv.includes("--debug");

// Banner to include at the top of the generated file
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/
`;

// Define external dependencies that should not be bundled
const externalDependencies = [
  "obsidian",
  "electron",
  "@codemirror/*",
  "@lezer/*",
  ...builtins,
];

// Build options common to both development and production
const buildOptions = {
  entryPoints: ["./src/main.tsx", "./src/styles.scss"],
  plugins: [
    stripUnusedZodLocales,
    sassPlugin({
      type: "css",
      precompile: (source) => {
        const devFlag = isDebug ? "$isDev: true;" : "$isDev: false;";
        return `${devFlag}\n${source}`;
      },
    }),
  ],
  bundle: true,
  platform: "browser",
  target: "es2017",
  external: externalDependencies,
  format: "cjs",
  sourcemap: isProd ? false : "inline",
  minify: isProd,
  banner: { js: banner },
  logLevel: "info",
  outdir: "build",
  resolveExtensions: [".js", ".jsx", ".ts", ".tsx"], // Ensure extensions are resolved
  alias: {
    src: "./src", // Add this to map the alias
    react: "preact/compat",
    "react-dom": "preact/compat",
  },
};

async function build() {
  if (!isProd) {
    // Development build with watch mode
    const context = await esbuild.context(buildOptions);

    // Start watching for file changes
    await context.watch();

    console.log("Watching for changes...");
  } else {
    // Production build (one-time build)
    await esbuild.build(buildOptions);
  }
}

// Execute the build function
build().catch((error) => {
  console.error(error);
  process.exit(1);
});
