import esbuild from "esbuild";
import process from "process";
import path from "path";
import fs from "fs";
import { builtinModules } from "node:module";
import { sassPlugin } from "esbuild-sass-plugin";

/**
 * zod's `locales/index.js` barrel re-exports error messages for ~20 languages
 * and is consumed as a namespace object (`z.locales`), so esbuild cannot
 * tree-shake it — it accounted for ~197 KB, over a quarter of the whole plugin.
 *
 * We only ever use zod's default (English) errors: nothing in `src` touches
 * `z.locales`, `errorMap`, `setErrorMap` or `z.config`. Swapping the barrel for
 * an `en`-only stub keeps validation messages identical.
 *
 * If a future change needs another zod locale, delete this plugin — the bundle
 * grows back, but nothing silently misbehaves.
 */
const stripUnusedZodLocales = {
  name: "strip-unused-zod-locales",
  setup(build) {
    build.onResolve({ filter: /locales[\\/]index\.js$/ }, (args) => {
      if (!args.importer.includes(`${path.sep}zod${path.sep}`)) {
        return null;
      }
      return { path: args.path, namespace: "zod-locales-stub" };
    });

    build.onLoad({ filter: /.*/, namespace: "zod-locales-stub" }, () => ({
      contents: `export { default as en } from ${JSON.stringify(
        path.resolve("node_modules/zod/v4/locales/en.js"),
      )};`,
      loader: "js",
      resolveDir: process.cwd(),
    }));
  },
};

/**
 * zod's JSON-Schema emitter is pulled in unconditionally (every schema
 * constructor assigns `inst._zod.processJSONSchema`), so esbuild cannot
 * tree-shake it — it costs ~17 KB, 6% of the plugin. Nothing in `src` calls
 * `toJSONSchema()`, so its three modules are replaced by throwing stubs.
 *
 * The stub must export every name zod itself imports or re-exports, listed
 * here explicitly. If zod adds another one, the build fails loudly with
 * "No matching export" — add it, or delete this plugin and take the 17 KB.
 */
const ZOD_JSON_SCHEMA_STUBS = {
  "to-json-schema": [
    "createStandardJSONSchemaMethod",
    "createToJSONSchemaMethod",
    "extractDefs",
    "finalize",
    "handleUnrepresentable",
    "initializeContext",
    "processSchema",
  ],
  "json-schema-processors": ["allProcessors", "toJSONSchema"],
  "json-schema-generator": ["JSONSchemaGenerator"],
};

const stripZodJsonSchema = {
  name: "strip-zod-json-schema",
  setup(build) {
    build.onLoad(
      {
        filter:
          /zod[\\/]v4[\\/]core[\\/](to-json-schema|json-schema-processors|json-schema-generator)\.js$/,
      },
      (args) => {
        const module = path.basename(args.path, ".js");
        return {
          contents: [
            "const unsupported = () => {",
            '  throw new Error("heatmap-tracker: zod JSON Schema support is stripped from this bundle (see esbuild.config.mjs).");',
            "};",
            ...ZOD_JSON_SCHEMA_STUBS[module].map(
              (name) => `export const ${name} = unsupported;`,
            ),
          ].join("\n"),
          loader: "js",
        };
      },
    );
  },
};

// Determine if we're in production mode
const isProd = process.argv.includes("--production");
const isDebug = process.argv.includes("--debug");

// Banner to include at the top of the generated file
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/
`;

// Define external dependencies that should not be bundled
const externalDependencies = [
  "obsidian",
  "electron",
  "@codemirror/*",
  "@lezer/*",
  ...builtinModules,
  ...builtinModules.map((name) => `node:${name}`),
];

/**
 * Dev builds write straight into the example vault's plugin folder (which has
 * a `.hotreload` marker), so Obsidian picks changes up without a second
 * watcher copying files around.
 */
const DEV_VAULT_PLUGIN_DIR = "EXAMPLE_VAULT/.obsidian/plugins/heatmap-tracker";
const outdir = isProd ? "build" : DEV_VAULT_PLUGIN_DIR;

// Build options common to both development and production
const buildOptions = {
  entryPoints: ["./src/main.tsx", "./src/styles.scss"],
  plugins: [
    stripUnusedZodLocales,
    stripZodJsonSchema,
    sassPlugin({
      type: "css",
      precompile: (source) => {
        const devFlag = isDebug ? "$isDev: true;" : "$isDev: false;";
        return `${devFlag}\n${source}`;
      },
    }),
  ],
  bundle: true,
  platform: "browser",
  target: "es2017",
  external: externalDependencies,
  format: "cjs",
  sourcemap: isProd ? false : "inline",
  minify: isProd,
  // Emit UTF-8 directly: without this esbuild escapes every non-ASCII
  // character in the bundled translations as \uXXXX, tripling their size.
  charset: "utf8",
  banner: { js: banner },
  logLevel: "info",
  outdir,
  resolveExtensions: [".js", ".jsx", ".ts", ".tsx"], // Ensure extensions are resolved
  alias: {
    src: "./src", // Add this to map the alias
    react: "preact/compat",
    "react-dom": "preact/compat",
  },
};

async function build() {
  fs.mkdirSync(outdir, { recursive: true });
  // Obsidian needs the manifest next to main.js, in both the build output and
  // the dev vault.
  fs.copyFileSync("manifest.json", path.join(outdir, "manifest.json"));

  if (!isProd) {
    // Development build with watch mode
    const context = await esbuild.context(buildOptions);

    // Start watching for file changes
    await context.watch();

    console.log(`Watching for changes, writing into ${outdir}`);
  } else {
    // Production build (one-time build)
    await esbuild.build(buildOptions);
  }
}

// Execute the build function
build().catch((error) => {
  console.error(error);
  process.exit(1);
});
