import esbuild from "esbuild";
import process from "process";
import path from "path";
import fs from "fs";
import builtins from "builtin-modules";
import { sassPlugin } from "esbuild-sass-plugin";

/**
 * zod's `locales/index.js` barrel re-exports error messages for ~20 languages
 * and is consumed as a namespace object (`z.locales`), so esbuild cannot
 * tree-shake it — it accounted for ~197 KB, over a quarter of the whole plugin.
 *
 * We only ever use zod's default (English) errors: nothing in `src` touches
 * `z.locales`, `errorMap`, `setErrorMap` or `z.config`. Swapping the barrel for
 * an `en`-only stub keeps validation messages identical.
 *
 * If a future change needs another zod locale, delete this plugin — the bundle
 * grows back, but nothing silently misbehaves.
 */
const stripUnusedZodLocales = {
  name: "strip-unused-zod-locales",
  setup(build) {
    build.onResolve({ filter: /locales[\\/]index\.js$/ }, (args) => {
      if (!args.importer.includes(`${path.sep}zod${path.sep}`)) {
        return null;
      }
      return { path: args.path, namespace: "zod-locales-stub" };
    });

    build.onLoad({ filter: /.*/, namespace: "zod-locales-stub" }, () => ({
      contents: `export { default as en } from ${JSON.stringify(
        path.resolve("node_modules/zod/v4/locales/en.js"),
      )};`,
      loader: "js",
      resolveDir: process.cwd(),
    }));
  },
};

/**
 * zod's JSON-Schema emitter (`core/to-json-schema.js` +
 * `core/json-schema-processors.js`) is pulled in unconditionally: every schema
 * constructor in `classic/schemas.js` assigns
 * `inst._zod.processJSONSchema = processors.<x>Processor`, and `ZodType`
 * exposes both `toJSONSchema()` and a `~standard.jsonSchema` getter. esbuild
 * therefore cannot tree-shake it, and it costs ~17 KB minified.
 *
 * We never convert a schema to JSON Schema: nothing in `src` calls
 * `toJSONSchema()` or reads `~standard`. Replacing both modules with stubs
 * whose exports throw keeps `parse`/`safeParse` byte-identical and turns the
 * unused path into a loud error instead of a silent wrong result.
 *
 * If a future change needs `z.toJSONSchema()`, delete this plugin.
 */
const ZOD_JSON_SCHEMA_MODULES = [
  "node_modules/zod/v4/core/to-json-schema.js",
  "node_modules/zod/v4/core/json-schema-processors.js",
];

/** Collect every exported binding name of an ESM file, aliases included. */
function collectExportNames(source) {
  const names = new Set();

  for (const match of source.matchAll(
    /^export\s+(?:async\s+)?(?:const|let|var|function\*?|class)\s+([A-Za-z_$][\w$]*)/gm,
  )) {
    names.add(match[1]);
  }

  for (const match of source.matchAll(/^export\s*\{([^}]*)\}/gm)) {
    for (const part of match[1].split(",")) {
      const name = part.trim().split(/\s+as\s+/)[1] ?? part.trim();
      if (name) {
        names.add(name);
      }
    }
  }

  names.delete("default");
  return [...names];
}

const stripZodJsonSchema = {
  name: "strip-zod-json-schema",
  setup(build) {
    const stubs = new Map();

    for (const modulePath of ZOD_JSON_SCHEMA_MODULES) {
      const absolute = path.resolve(modulePath);
      const names = collectExportNames(fs.readFileSync(absolute, "utf8"));

      if (names.length === 0) {
        throw new Error(
          `strip-zod-json-schema: no exports found in ${modulePath}; zod's layout changed, update or remove this plugin.`,
        );
      }

      stubs.set(
        absolute,
        [
          "const unsupported = () => {",
          '  throw new Error("heatmap-tracker: zod JSON Schema support is stripped from this bundle (see esbuild.config.mjs).");',
          "};",
          ...names.map((name) => `export const ${name} = unsupported;`),
        ].join("\n"),
      );
    }

    build.onLoad(
      {
        filter:
          /zod[\\/]v4[\\/]core[\\/](to-json-schema|json-schema-processors)\.js$/,
      },
      (args) => {
        const contents = stubs.get(args.path);
        return contents ? { contents, loader: "js" } : null;
      },
    );
  },
};

// Determine if we're in production mode
const isProd = process.argv.includes("--production");
const isDebug = process.argv.includes("--debug");

// Banner to include at the top of the generated file
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/
`;

// Define external dependencies that should not be bundled
const externalDependencies = [
  "obsidian",
  "electron",
  "@codemirror/*",
  "@lezer/*",
  ...builtins,
];

// Build options common to both development and production
const buildOptions = {
  entryPoints: ["./src/main.tsx", "./src/styles.scss"],
  plugins: [
    stripUnusedZodLocales,
    stripZodJsonSchema,
    sassPlugin({
      type: "css",
      precompile: (source) => {
        const devFlag = isDebug ? "$isDev: true;" : "$isDev: false;";
        return `${devFlag}\n${source}`;
      },
    }),
  ],
  bundle: true,
  platform: "browser",
  target: "es2017",
  external: externalDependencies,
  format: "cjs",
  sourcemap: isProd ? false : "inline",
  minify: isProd,
  // Emit UTF-8 directly: without this esbuild escapes every non-ASCII
  // character in the bundled translations as \uXXXX, tripling their size.
  charset: "utf8",
  banner: { js: banner },
  logLevel: "info",
  outdir: "build",
  resolveExtensions: [".js", ".jsx", ".ts", ".tsx"], // Ensure extensions are resolved
  alias: {
    src: "./src", // Add this to map the alias
    react: "preact/compat",
    "react-dom": "preact/compat",
  },
};

async function build() {
  if (!isProd) {
    // Development build with watch mode
    const context = await esbuild.context(buildOptions);

    // Start watching for file changes
    await context.watch();

    console.log("Watching for changes...");
  } else {
    // Production build (one-time build)
    await esbuild.build(buildOptions);
  }
}

// Execute the build function
build().catch((error) => {
  console.error(error);
  process.exit(1);
});
